// Demo 8 - Complete Application; LV
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Demo8.Models;

[Table("Film")]
public partial class Film
{
    [Key]
    public int FilmPK { get; set; }

    [Required]
    [StringLength(255)]
    [Display(Name = "Title")]
    public string MovieTitle { get; set; }

    [Required]
    [StringLength(100)]
    [Display(Name = "Tag Line")]
    public string PitchText { get; set; }

    [Display(Name = "Budget")]
    public long? AmountBudgeted { get; set; }

    public int? RatingFK { get; set; }

    public string Summary { get; set; }

    [StringLength(50)]
    public string ImageName { get; set; }

    [Column(TypeName = "date")]
    [Display(Name = "Date")]
    public DateTime? DateInTheaters { get; set; }

    [InverseProperty("FilmFKNavigation")]
    public virtual ICollection<FilmReview> FilmReviews { get; set; } = new List<FilmReview>();

    [ForeignKey("RatingFK")]
    [InverseProperty("Films")]
    [Display(Name = "Rating")]
    public virtual FilmRating RatingFKNavigation { get; set; }
}