// Demo 8 - Complete Application; LV
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Demo8.Models;

public partial class RWStudiosContext : DbContext
{
    public RWStudiosContext(DbContextOptions<RWStudiosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Contact> Contacts { get; set; }

    public virtual DbSet<Film> Films { get; set; }

    public virtual DbSet<FilmRating> FilmRatings { get; set; }

    public virtual DbSet<FilmReview> FilmReviews { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Contact>(entity =>
        {
            entity.HasOne(d => d.UserRoleFKNavigation).WithMany(p => p.Contacts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Contact_UserRole");
        });

        modelBuilder.Entity<Film>(entity =>
        {
            entity.HasOne(d => d.RatingFKNavigation).WithMany(p => p.Films).HasConstraintName("FK_Film_FilmRating");
        });

        modelBuilder.Entity<FilmReview>(entity =>
        {
            entity.HasOne(d => d.ContactFKNavigation).WithMany(p => p.FilmReviews)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FilmReview_Contact");

            entity.HasOne(d => d.FilmFKNavigation).WithMany(p => p.FilmReviews)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FilmReview_Film");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}