// Demo 8 - Complete Application; LV
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Demo8.Models;

[Table("UserRole")]
public partial class UserRole
{
    [Key]
    public int UserRolePK { get; set; }

    [Required]
    [StringLength(20)]
    public string UserRoleName { get; set; }

    [Required]
    [StringLength(75)]
    public string UserRoleFunction { get; set; }

    [InverseProperty("UserRoleFKNavigation")]
    public virtual ICollection<Contact> Contacts { get; set; } = new List<Contact>();
}