//Demo 7 - Shopping Cart; LV
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Demo7.Models;

[Table("LoginInfo")]
public partial class LoginInfo
{
    [Key]
    public int UserPK { get; set; }

    [Required]
    [StringLength(50)]
    [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Upper and lower case letters")]
    [Display(Name = "Username")]
    public string Uname { get; set; }

    [Required]
    [StringLength(255)]
    [RegularExpression(@"^[a-zA-Z0-9\*\$]+$", ErrorMessage = "Letters, digits, *, $")]
    [Display(Name = "Password")]
    public string UPass { get; set; }

    [Required]
    [StringLength(50)]
    [RegularExpression(@"^[a-zA-Z]+\s[a-zA-Z]+$", ErrorMessage = "First and Last Name; Upper and lower case letters")]
    [Display(Name = "Full Name", Prompt = "First and Last Name")]
    public string FullName { get; set; }

    //[Required] Removed "required"; role is set in code (see SignUp action method in AccountController)
    [StringLength(50)]
    public string URole { get; set; }

    [InverseProperty("CustomerFKNavigation")]
    public virtual ICollection<tblOrder> tblOrders { get; set; } = new List<tblOrder>();
}