// Demo 8 - Complete Application; LV
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Demo8.Models;

[Table("FilmRating")]
public partial class FilmRating
{
    [Key]
    public int RatingPK { get; set; }

    [Required]
    [StringLength(50)]
    public string Rating { get; set; }

    [InverseProperty("RatingFKNavigation")]
    public virtual ICollection<Film> Films { get; set; } = new List<Film>();
}