// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HandOnEx6.Models;

[Table("Category")]
public partial class Category
{
    [Key]
    public int CategoryPK { get; set; }

    [Required]
    [StringLength(50)]
    public string CategoryName { get; set; }

    [Required]
    [StringLength(50)]
    public string CategoryImage { get; set; }

    [StringLength(50)]
    public string Thumbnail { get; set; }

    [Required]
    [StringLength(50)]
    public string Description { get; set; }

    [StringLength(50)]
    public string TinyThumb { get; set; }

    [InverseProperty("CategoryFKNavigation")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    [InverseProperty("CategoryFKNavigation")]
    public virtual ICollection<SubCategory> SubCategories { get; set; } = new List<SubCategory>();
}