// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HandOnEx6.Models;

[Table("Product")]
public partial class Product
{
    [Key]
    public int ProductPK { get; set; }

    public int CategoryFK { get; set; }

    public int SubCategoryFK { get; set; }

    [Required]
    [StringLength(50)]
    public string ModelNumber { get; set; }

    [Required]
    [StringLength(50)]
    public string ModelName { get; set; }

    [StringLength(50)]
    public string ProductImage { get; set; }

    [Column(TypeName = "money")]
    public decimal UnitCost { get; set; }

    [Required]
    [Column(TypeName = "ntext")]
    public string Description { get; set; }

    [StringLength(50)]
    public string Thumbnail { get; set; }

    [StringLength(50)]
    public string Availability { get; set; }

    [ForeignKey("CategoryFK")]
    [InverseProperty("Products")]
    public virtual Category CategoryFKNavigation { get; set; }

    [ForeignKey("SubCategoryFK")]
    [InverseProperty("Products")]
    public virtual SubCategory SubCategoryFKNavigation { get; set; }

    [InverseProperty("ProductFKNavigation")]
    public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; } = new List<tblOrderDetail>();
}