// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HandOnEx6.Models;

[Table("SubCategory")]
public partial class SubCategory
{
    [Key]
    public int SubCategoryPK { get; set; }

    public int CategoryFK { get; set; }

    [Required]
    [StringLength(50)]
    public string SubCategoryName { get; set; }

    [StringLength(50)]
    public string SubCategoryImage { get; set; }

    [StringLength(50)]
    public string Thumbnail { get; set; }

    [Required]
    [Column(TypeName = "ntext")]
    public string Description { get; set; }

    [ForeignKey("CategoryFK")]
    [InverseProperty("SubCategories")]
    public virtual Category CategoryFKNavigation { get; set; }

    [InverseProperty("SubCategoryFKNavigation")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}