// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HandOnEx6.Models;

[Table("tblOrder")]
public partial class tblOrder
{
    [Key]
    public int OrderPK { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? OrderDate { get; set; }

    public int CustomerFK { get; set; }

    [ForeignKey("CustomerFK")]
    [InverseProperty("tblOrders")]
    public virtual LoginInfo CustomerFKNavigation { get; set; }

    [InverseProperty("OrderFKNavigation")]
    public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; } = new List<tblOrderDetail>();
}