//Demo 7 - Shopping Cart; LV
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Demo7.Models;

[Table("tblOrderDetail")]
public partial class tblOrderDetail
{
    [Key]
    public int OrderDetailPK { get; set; }

    public int ProductFK { get; set; }

    public int OrderFK { get; set; }

    public int Quantity { get; set; }

    [ForeignKey("OrderFK")]
    [InverseProperty("tblOrderDetails")]
    public virtual tblOrder OrderFKNavigation { get; set; }

    [ForeignKey("ProductFK")]
    [InverseProperty("tblOrderDetails")]
    public virtual Product ProductFKNavigation { get; set; }
}